### ISSUE TITLE
Bulid issue

### ISSUE THREAD

**Issue by billti** [brendan-duncan/webgpu_inspector#14]
I just cloned and tried to build as per the instructions, and it's failing with the below. Any ideas? Perhaps the sister projects (webgpu_recorder and wgsl_reflect) need to be built as well rather than installed from npm to be up to date?

I can dig into it if this shouldn't be happening, just thought you might know off the top of your head. Thanks!

```
$ npm run build

> webgpu_inspector@0.5.0 build
> rollup -c rollup.config.js


src/webgpu_inspector_core.js → extensions/chrome/webgpu_inspector_core.js...
created extensions/chrome/webgpu_inspector_core.js in 340ms

src/webgpu_inspector.js → extensions/chrome/webgpu_inspector.js...
created extensions/chrome/webgpu_inspector.js in 336ms

src/webgpu_recorder_loader.js → extensions/chrome/webgpu_recorder_loader.js...
[!] (plugin stringer) Error: Could not load webgpu_recorder_core_func (imported by src/webgpu_recorder_loader.js): ENOENT: no such file or directory, open 'extensions/chrome/webgpu_recorder.js.map'
Error: Could not load webgpu_recorder_core_func (imported by src/webgpu_recorder_loader.js): ENOENT: no such file or directory, open 'extensions/chrome/webgpu_recorder.js.map'
    at Object.readFileSync (node:fs:457:20)
    at Object.load (/Users/billti/src/webgpu_inspector/rollup.config.js:92:46)
    at /Users/billti/src/webgpu_inspector/node_modules/rollup/dist/shared/rollup.js:22879:40
```

**Comment by brendan-duncan** [comment]
Did you run npm install to get the dependencies?

**Comment by billti** [comment]
I did.

**Comment by brendan-duncan** [comment]
hmmm....
the recorder_core_func stuff is new. I'll try cloning a new repo, make sure I didn't do something that "works on my machine".

**Comment by brendan-duncan** [comment]
Looks like I did break it. I'll get it fixed up as soon as I can.

**Comment by brendan-duncan** [comment]
It should be working now if you pull.
I had some leftover old code in there for a file that was still in my main checkout.

**Comment by billti** [comment]
Built fine - thanks!
