### ISSUE TITLE
Is it possible to view textures that declare multiple > 1 mip levels?

### ISSUE THREAD

**Issue by mreinstein** [brendan-duncan/webgpu_inspector#19]
I have a bloom shader that works by successively downsampling a frame into lower resolution images, upscaling and then combining these.  The 2 downsample textures each declare multiple mip levels (7). Is there a way to inspect the visual output of these textures per individual mip level?

Thanks for a great tool by the way! This is the most stable webgpu tool I've encountered so far!

**Comment by brendan-duncan** [comment]
I've been meaning to add texture mip inspection. I'll try to get to that soon.

**Comment by mreinstein** [comment]
That would be super helpful! I'm trying to debug why my bloom shader starts freaking when items giving off bloom effect overlap the viewport edge:
<img width="837" alt="Screenshot 2024-07-21 at 2 29 29 PM" src="https://github.com/user-attachments/assets/418741be-c121-4b9c-ba27-23508118c1c2">

I suspect something is going on in one of the compute shader passes with bad logic in the blur function when writing to the edges of the buffer.  Being able to look at these mips and pinpoint where would be fantastic.

**Comment by brendan-duncan** [comment]
I updated the git version adding  a "Mip Level" UI to the texture inspector so you can select which mip level to view. I haven't done a lot of testing yet, I just threw it in there in between making dinner and chasing the kids around. I know the tooltip for pixel data on the image isn't quite right yet for non-zero mip levels. And there's lots of other texture view stuff I'd like to add at some point, like zooming and all that good stuff. One day...

![image](https://github.com/user-attachments/assets/dfb03b7d-07be-4e38-8ef0-2b627b5abb96)

**Comment by mreinstein** [comment]
Amazing, I was immediately able to see the problem in my shader with this change. Thank you so much!
