### ISSUE TITLE
Compute pass information not present

### ISSUE THREAD

**Issue by gitbetter** [brendan-duncan/webgpu_inspector#20]
I think this is probably the only good WebGPU gpu debugger available and I've been using it extensively. The only important thing that seems to be missing is that compute pass information doesn't seem to show up anywhere, as far as I can tell.

In this capture I have two compute passes, one before and one after all those buffer writes in the middle. I can't seem to find any information regarding compute shaders anywhere though, so maybe that's not implemented yet? Would be worthwhile to add that in.

![Screenshot 2024-07-23 134323](https://github.com/user-attachments/assets/95b749e4-8f2a-4b1d-8bed-07e31be906e5)

**Comment by brendan-duncan** [comment]
That is odd, it does do compute pass captures already. I'm very curious why yours aren't recorded. Any chance for a repo I can test?
![image](https://github.com/user-attachments/assets/76ed41b1-9d11-477a-b9e3-bff298344f8d)

**Comment by gitbetter** [comment]
Hey, sorry about that 😅 my mistake.. My first inkling was that the inspector wasn't set up to show compute passes, but I think it was just an issue on my end.
I'm working on a WebGPU engine and it seems I was skipping the corresponding compute `begin` and `end` calls on my end for some reason.
https://github.com/Sunset-Studios/Sundown/blob/c0cab9f3ad49502e7fde2492f9e606699c5d12a9/engine/src/renderer/render_graph.js#L962

I can see compute passes just fine now. Sorry for the bother!
