### ISSUE TITLE
Inspect Start, Capture, or Record does not work

### ISSUE THREAD

**Issue by LuciNyan** [brendan-duncan/webgpu_inspector#3]
> Thanks so much for the amazing WebGPU Inspector you've created! 🚀

# Bug report

## Description / Observed Behavior

When inspecting the following page, the Inspect Start, Capture, and Record functions all appear to be non-functional. I've tried refreshing the page as well as clicking around to focus the page, but nothing seems to resolve the issue.

https://github.com/brendan-duncan/webgpu_inspector/assets/22126563/34866b22-1ed4-480b-9eae-04f106d2a775

## Reproduction
https://cobe.vercel.app/

**Comment by brendan-duncan** [comment]
Unless I'm missing something, this page is WebGL, not WebGPU.

**Comment by LuciNyan** [comment]
Thank you! and sorry for the interruption.
