### ISSUE TITLE
Different color for hierarchy levels

### ISSUE THREAD

**Issue by mvaligursky** [brendan-duncan/webgpu_inspector#4]
I'd love to have different colors for different levels in the debug markers to make it more obvious. Currently we use 3 levels and this would make it easier to read.

![Screenshot 2024-04-26 at 09 55 44](https://github.com/brendan-duncan/webgpu_inspector/assets/59932779/4eab339b-c782-474e-9c1c-59a85d21adc5)

I also wonder if there is a way to avoid these lines being added:
![Screenshot 2024-04-26 at 09 57 36](https://github.com/brendan-duncan/webgpu_inspector/assets/59932779/420aecb0-9226-469c-b294-1658fbe18bd9)

**Comment by brendan-duncan** [comment]
The renderpass groups are useful when you don't have a debug group for each render pass, but I agree they aren't very useful when they are 1:1 with debug groups. I can see if I can reduce their usage in these situations.

**Comment by mvaligursky** [comment]
Fantastic tool by the way, very happy to find it!

**Comment by mvaligursky** [comment]
> The renderpass groups are useful when you don't have a debug group for each render pass, but I agree they aren't very useful when they are 1:1 with debug groups. I can see if I can reduce their usage in these situations.

If they'd show up only at the start of the RenderPass that would be ok, but they seem to show up inside each 'start' debug marker as well, and that is very redundant.

**Comment by brendan-duncan** [comment]
I've been playing around with the styling, alternating debug group background colors. 
I took out the renderpass group headers that were always put into debug groups.

The grouping of commands by render pass and debug group gets really complicated when there are multiple command encoders, particularly when their commands are interleaved. It might be better to organize the commands in their WebGPU queue timeline order, rather than the order they were called. Maybe an experiment for another day.

![image](https://github.com/brendan-duncan/webgpu_inspector/assets/3642099/ec79224f-7987-4ade-9281-a326c642d898)

**Comment by mvaligursky** [comment]
Hi that looks much better, but I'd be keen to have those a very different colors, not just shades of gray. Something like this (but in a hierarchy format as you have it currently):

![image](https://github.com/brendan-duncan/webgpu_inspector/assets/59932779/def9b579-cac8-4e97-8b70-7cfa456cde0f)

**Comment by brendan-duncan** [comment]
With your rainbow colors. I'll play around with it a bit more later, I still haven't decided myself if this is useful or obnoxious.
![image](https://github.com/brendan-duncan/webgpu_inspector/assets/3642099/81c3180f-d1c9-47dd-b678-4ef9551b0b43)

**Comment by mvaligursky** [comment]
Hah yeah this is really colorful :)
I changed the way I use the groups now to have less levels (only 3), so it'd be less crazy .. but I see your concern too. Maybe less colorful but not just shades of gray? :)

**Comment by brendan-duncan** [comment]
I think desaturating the colors a bit helps,
![image](https://github.com/brendan-duncan/webgpu_inspector/assets/3642099/db9fd8c1-bb9d-4ca3-8eb6-15725ee89cbb)

**Comment by brendan-duncan** [comment]
Added some shadows to help separate the groups 
![image](https://github.com/brendan-duncan/webgpu_inspector/assets/3642099/1ee86934-2dbc-4eb7-ae4c-eee46e9da665)

**Comment by mvaligursky** [comment]
Honestly? It looks great, and much easier to read compared to the initial screenshot. Thanks!

**Comment by Twinklebear** [comment]
I like the look here too, though agree a bit more desaturated/devaluated would probably help it not be as visually "strong"

**Comment by brendan-duncan** [comment]
I submitted the store version update for review. It also has some fixes for uniform/storage buffer views.

**Comment by brendan-duncan** [comment]
I think the colors aren't quite as strong in the real devtools page. I think maybe the Windows snapshot screen capture doesn't like my monitor being in HDR mode.

**Comment by brendan-duncan** [comment]
The updates are on the chrome store version now.
