### ISSUE TITLE
Improve Large Buffer Views

### ISSUE THREAD

**Issue by Twinklebear** [brendan-duncan/webgpu_inspector#6]
Reminder issue from #5 , when viewing large buffers in https://github.com/Twinklebear/webgpu-marching-cubes , the tab will hang as the data is drawn and gets slow with so many elements on the page. Some basic pagination should help improve the performance here, and it'd be awesome to have some search/filtering support or jump to index support to more easily navigate large buffers in the inspector.

**Comment by brendan-duncan** [comment]
I started playing around with filtering large buffer views to not kill the html panel. If there are more than 100 elements in a buffer array, then it limits the view to a set count with an offset. You can use the offset scrollbar to scrub through the buffer data and it updates pretty interactively.

![image](https://github.com/brendan-duncan/webgpu_inspector/assets/3642099/d5fb2c7a-49f3-4a94-a711-86acb3b413fd)

**Comment by Twinklebear** [comment]
This looks great!

**Comment by brendan-duncan** [comment]
I styled it a little bit more, and will submit a chrome store update. It usually takes a day or two for the chrome store to update a new version.

**Comment by Twinklebear** [comment]
Awesome, than you!
