### ISSUE TITLE
Command registration to RenderBundleEncoder not captured

### ISSUE THREAD

**Issue by emadurandal** [brendan-duncan/webgpu_inspector#9]
Hi, I am developing a Web3D library and just working on WebGPU support.
In my library, drawing is always done using the render bundle.
But, the current WebGPU Inspector does not seem to capture the registration of commands to the RenderBundleEncoder (such as setBindGroups and draw).

Is it possible to improve the Inspector so that the registration of commands to the RenderBundleEncoder is also captured?

![image](https://github.com/brendan-duncan/webgpu_inspector/assets/3821214/995aaae3-347f-4be8-bfa1-5c12c867ba74)

**Comment by brendan-duncan** [comment]
One option would be to capture frame 0 (or whichever frame you're creating the render bundles in). You can change the Capture from Immediate to Frame.

That will be tough to capture render bundles so they're available from any frame capture, but I'll try to figure it out.

Normally it doesn't capture commands until you request the capture, but by the time you're capturing the frame, the render bundle has already been created. To generally capture render bundles, it would always have to capture commands that are part of a render bundle. I can probably do that, possibly with an option.

The other challenge I'll have to figure out is the UI. The Frame Capture lays out the commands in the frame, but I'll need to figure out a good way to lay out the commands in a render buffer. Is it a collapsed group under the execute command? Is is something in the inspection of the execute command? Is it something in the inspection of the RenderBundle object? I'll have to play around with it, figure out something that works with the UI and doesn't clutter too much. RenderBundles could potentially be quite large.

So yeah, definitely want to do this, it'll take a bit to figure out.

**Comment by emadurandal** [comment]
> One option would be to capture frame 0 (or whichever frame you're creating the render bundles in). You can change the Capture from Immediate to Frame.

The screenshot above was captured with the code in the library modified to disable the RenderBundle cache and register commands to the RenderBundleEncoder every frame.
Nevertheless, the command registration to the RenderBundleEncoder does not appear to be captured.

> So yeah, definitely want to do this, it'll take a bit to figure out.
Thank you very much. I understand that this is probably a hard task. If experimental ones are implemented, I can report some kind of usage feedback.

**Comment by brendan-duncan** [comment]
I started on this, but still have a ways to go. It will at least capture the RenderBundle objects for inspection now, but not its command contents. Inspecting a RenderBundle object in the inspector panel will display the descriptor the RenderBundleEncoder was created with. The current changes have been pushed to git.

Still have a ways to go, but the family is telling me to get off the computer :-).

**Comment by emadurandal** [comment]
Thank you for your prompt response. But please take it easy and spend time with your family😌

**Comment by emadurandal** [comment]
I tried the latest inspector and confirmed that the addition of commands to the RenderBundleEncoder has been traced. Thank you! It’s very useful!
And while I understand that this is only an interim response, I have noticed one thing.

![image](https://github.com/brendan-duncan/webgpu_inspector/assets/3821214/a6668099-8d4c-4dff-a823-6636134f0ce0)

Creating a RenderBundleEncoder and adding commands to a RenderBundleEncoder should be operations unrelated to RenderPass, but they are currently in and out of the RenderPass frame in the UI. How to display the RenderBundleEncoder on the UI seems to be an issue in the future.

**Comment by brendan-duncan** [comment]
I'll work on improving the command grouping with render bundles. Command grouping is a really hard problem with WebGPU.

**Comment by brendan-duncan** [comment]
I'm running out of colors...
![image](https://github.com/brendan-duncan/webgpu_inspector/assets/3642099/4ee1f23c-7328-42fd-8daa-1b0754485de6)

**Comment by brendan-duncan** [comment]
Started playing around with displaying the commands that get executed by executeBundles. This attempt puts the commands in the command inspection.

These changes are in the render_bundle branch.

![image](https://github.com/brendan-duncan/webgpu_inspector/assets/3642099/94ca80e6-ffe0-4172-b42d-58ea94218deb)

**Comment by emadurandal** [comment]
It is great to be able to trace the contents of executeBundles.
However, in the current version ( 48621132193183e7227ace5237b5393f8aa3baa9 ) the behaviour of the UI seems a bit unstable. Even if you open the accordion for each item on the right-hand side, it may immediately close by itself.

![image](https://github.com/brendan-duncan/webgpu_inspector/assets/3821214/3f22814e-bea5-42bd-a318-84aee251d91f)

Anyway, many libraries will be using RenderBundle to speed up the rendering, so this feature addition is very good news.

**Comment by brendan-duncan** [comment]
The "immediately close by itself" is probably because there are still some buffers being read over (the "Loading images" status line), and there's a bug where it refreshes the GUI as the buffers are read in. But there's probably a better way to present the UI for them, I don't really like the current implementation, it was just the easiest to check if I was capturing the bundle commands correctly.  Maybe as a collapsible group in the command list itself, like a shadow DOM sort of thing... I'm still playing around with it.

I wish I could use render bundles in the Unity WebGPU driver I develop, but the driver is too low level and I can't really use them. Maybe one day I'll figure out how fit them in, but since WebGPU is the only one with that concept (besides GL's display lists), the concept doesn't really fit into a cross platform engine very well.

**Comment by brendan-duncan** [comment]
Playing around with the UI some more. Moved the expanded renderBundle commands into the command list, collapsed by default. You can click on the + on the executeBundles command and it will expand out the render bundle commands that are executed by it. Selecting a command in the render bundle will show the inspection info for that command.

![image](https://github.com/brendan-duncan/webgpu_inspector/assets/3642099/a8a928bb-c78b-46a7-ae0a-286ab8a81cd0)

**Comment by emadurandal** [comment]
I have tried the latest version and it is working very nice.
Thank you very much!

![image](https://github.com/brendan-duncan/webgpu_inspector/assets/3821214/ccdf1699-1290-4471-a9c1-eb9431bfb9d8)

**Comment by brendan-duncan** [comment]
The recent changes have been released to the chrome store version now.

**Comment by emadurandal** [comment]
Thank you. As for me, I think the purpose of this Issue has been fulfilled and you can close it at any time
